# Generated by Django 4.0.3 on 2022-03-23 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=50)),
                ('attendance', models.CharField(max_length=20)),
                ('on_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
