# Generated by Django 4.0.3 on 2022-03-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handleatten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='studentsattendance',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='handleatten.student'),
        ),
    ]
