# Generated by Django 4.0.3 on 2022-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleatten', '0002_student_alter_studentsattendance_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsattendance',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
