# Generated by Django 4.0.3 on 2022-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleatten', '0003_remove_studentsattendance_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsattendance',
            name='attendance',
            field=models.JSONField(),
        ),
    ]
